west2-online/fzuhelper-app

.gitignore, README.md, app.json, docs/build/android.md, docs/build/ios.md, package.json
=> Android Build Docs

app/(root)/_layout.tsx
1. 修正因 #29 错误 merge 导致的 (root)/_layout.tsx 代码被覆盖的问题
=> fix: (root)/_layout.tsx code error

.gitignore, app.config.ts, inject-ios-prebuild.ts, ios/ci_scripts/ci_post_clone.sh, scripts/ci_post_clone.sh
依据文档：https://www.richinfante.com/2024/11/18/running-expo-prebuild-in-xcode-cloud 实现
=> feat: support xcode cloud compiling

app/(guest)/web.tsx
https://github.com/facebook/react-native/pull/45892
=> fix: error caused by `BackHandler.removeListener` being removed

api/backend.d.ts, api/generate/classroom.ts, api/generate/common.ts, api/generate/course.ts, api/generate/index.ts, api/generate/paper.ts, api/generate/types.ts, app/toolbox/academic/credits.tsx, app/toolbox/academic/gpa.tsx, app/toolbox/academic/grades.tsx, app/toolbox/academic/unified-exam.tsx, app/toolbox/empty-room.tsx, app/toolbox/exam-room.tsx, app/toolbox/paper.tsx
鉴于目前各个功能实现的 PR 中经常出现自行重新定义数据类型，而不是直接使用 openapi 接口生成的类型的情况，此 Pull Request 提供了一种从接口请求函数中推导返回数据类型的实用工具及其示例，以简化开发流程。
=> 增加对接口返回值的类型推断辅助工具

app/(guest)/web.tsx, components/HeaderIcon.tsx, components/WheelPickerRow.tsx, utils/course.ts
1. 由于 `@/api/backend.d.ts` 类型变更导致的部分文件类型导入错误
2. 修正部分组件（**不包含课表**）的样式警告
=> 修正类型错误以及样式警告

app/(tabs)/toolbox.tsx
Resolve the entry issue for 嘉熙讲坛 by updating the tool data structure and ensuring proper routing functionality.
=> 修复嘉熙讲坛入口问题

api/backend.d.ts, app/(guest)/web.tsx, app/(tabs)/toolbox.tsx, app/devtools/index.tsx, app/toolbox/academic/credits.tsx, app/toolbox/academic/gpa.tsx, app/toolbox/academic/plan.tsx, app/toolbox/academic/unified-exam.tsx, components/academic/CreditCard.tsx, components/course/schedule-detail-dialog.tsx, lib/webview.ts
1. 修正`Loading`组件和`SafeAreaView`使用；
2. 统一UI，获取时间移动到下方；
3. 完成培养计划功能；
4. 优化`web`传参和带cookie时的跳转逻辑，在web页检查和更新cookie，然后加载页面；
5. 移除web下拉刷新，避免安卓平台web下滑页面和下拉刷新手势冲突的问题；
6. 清除cookie改回全部清除，解决安卓平台过期cookie也在web中被发送导致无法访问的问题
* 培养计划功能由于后端传回的url多了id字段导致无法使用，等待后端解决
=> 学业状况内功能和web完善

.github/workflows/build-master.yml, app.config.ts, app/(tabs)/user.tsx
=> 帮助与反馈跳转测试群，允许安卓明文解决智慧餐厅访问问题

app/_layout.tsx, app/toolbox/academic/index.tsx, components/download-progress.tsx, components/loading.tsx, utils/android-update.ts, utils/download-manager.ts
增加LoadingDialog组件并应用于培养计划；
安卓自更新显示下载进度
=> 培养计划加载、自更新进度显示优化

app/common/academic-calendar.tsx, components/tab-flatlist.tsx, components/ui/tabs.tsx
- 补全圆角设计
- 修复闪退 https://github.com/facebook/react-native/issues/14198
=> TabFlatList修正

app/devtools/learning-center-api.tsx, app/toolbox/learning-center/available-seats.tsx, app/toolbox/learning-center/qr-scanner.tsx, app/toolbox/learning-center/seat-time-status.tsx, app/toolbox/learning-center/time-select.tsx, components/learning-center/history-appointment-card.tsx, components/learning-center/learning-center-map.tsx, components/learning-center/seat-card.tsx, utils/learning-center/api-service.ts, utils/learning-center/date.ts, utils/learning-center/seats.ts
=> 学习中心修正与功能增强

app/settings/appearance.tsx
https://github.com/ivpusic/react-native-image-crop-picker/issues/1367#issuecomment-841350648
=> 修复安卓选择壁纸不支持HEIC等格式图片的问题

app/toolbox/learning-center/available-seats.tsx, components/classroom-list.tsx, components/learning-center-seats-list.tsx, components/learning-center/seat-card.tsx, components/learning-center/seat-overview.tsx, types/learning-center.d.ts, utils/learning-center/seats.ts
=> 重构学习中心选座页面，优化性能

app/(learning-center)/_layout.tsx, app/(learning-center)/devtools/learning-center-api.tsx, app/(learning-center)/toolbox/learning-center/available-seats.tsx, app/(learning-center)/toolbox/learning-center/history.tsx, app/(learning-center)/toolbox/learning-center/index.tsx, app/(learning-center)/toolbox/learning-center/qr-scanner.tsx, app/(learning-center)/toolbox/learning-center/seat-time-status.tsx, app/(learning-center)/toolbox/learning-center/time-select.tsx, app/_layout.tsx, context/learning-center.tsx, lib/constants.ts
=> 使用 Context 重构学习中心 API Token 相关逻辑

api/generate/common.ts, app/(tabs)/toolbox.tsx, app/toolbox/office-notice.tsx
=> 增加 教务处通知 页面

modules/native-widget/android/src/main/java/com/helper/west2ol/fzuhelper/CourseScheduleWidgetConfigurationActivity.kt, modules/native-widget/android/src/main/java/com/helper/west2ol/fzuhelper/CourseScheduleWidgetProvider.kt, modules/native-widget/android/src/main/java/com/helper/west2ol/fzuhelper/NextClassWidgetProvider.kt, modules/native-widget/android/src/main/res/layout/next_class_widget_configuration.xml, modules/native-widget/android/src/main/res/layout/next_class_widget_provider.xml
=> fix-course-widget

app/toolbox/academic/grades.tsx, app/toolbox/onekey-comment/form.tsx, app/toolbox/onekey-comment/index.tsx, components/ui/float-modal.tsx
1. 修复评议时没有等待请求完毕的问题
2. 欢迎页对齐问题
3. Loading 态，下拉刷新
4. 输入框大小优化
5. 输入时键盘跟随问题
6. 随机选择选项
7. 检查 cookie 有效性
8. 验证码拉取失败重试一次，输入不能为空
=> 一键评议逻辑和样式调优

app/toolbox/learning-center/available-seats.tsx, app/toolbox/learning-center/seat-time-status.tsx, context/learning-center.tsx
useEffect依赖fetchSeatStatus，fetchSeatStatus依赖api，api没有用useMemo包裹，所以出现了重新调用
不知道为什么debug下不会出现
=> 修复从座位状态进入子页面后座位状态页面自动刷新问题

modules/native-widget/android/src/main/java/com/helper/west2ol/fzuhelper/NextClassWidgetProvider.kt
=> chore: 下节课小组件正方形模式下垂直居中

api/backend.d.ts, api/generate/academic.ts, app/toolbox/academic/credits.tsx, components/academic/CreditCard.tsx
feat: 更新学分统计相关API，支持辅修和更准确的分数计算（非辅修的就不显示 Tab 栏）
=> feat: 更新学分统计相关API，支持辅修和更准确的分数计算
